Repository FIUS/ICGE, pull requests merged in 2018-10, with the labels that each got.

#14 Add line breaking to the log
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/swing/SwingView.java
Labels: enhancement

#21 Fix the scroll bug
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/swing/SimPanel.java
Labels: bug

#57 Fix 2 bugs that occured when 0 entities alive
  src/main/java/de/unistuttgart/informatik/fius/icge/Engine.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/swing/SimPanel.java
Labels: High Priority

#58 simulation/Entity: Make `Entity` method `getDirection()` public
  src/main/java/de/unistuttgart/informatik/fius/icge/simulation/Entity.java
Labels: enhancement

#70 workbench/tools: Preceding visual feedback for tools
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/swing/SimPanel.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/AbstractSpawnEntityTool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/AbstractTool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/AreaTool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/DespawnTool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/SelectionTool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/SpawnCoinTool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/Tool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/ToolHandler.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/WallCreationTool.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/WallDemolishingTool.java
Labels: enhancement

#75 simulation, territory: consistent accessor methods
  src/main/java/de/unistuttgart/informatik/fius/icge/simulation/Entity.java
  src/main/java/de/unistuttgart/informatik/fius/icge/simulation/Simulation.java
  src/main/java/de/unistuttgart/informatik/fius/icge/territory/Territory.java
  src/main/java/de/unistuttgart/informatik/fius/icge/territory/WorldObject.java
Labels: enhancement

#82 workbench/swing/ToolBar: Add the speed slider
  src/main/java/de/unistuttgart/informatik/fius/icge/simulation/Simulation.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/swing/SwingView.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/swing/ToolBar.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/SimulationController.java
  src/main/java/de/unistuttgart/informatik/fius/icge/workbench/tools/ToolHandler.java
Labels: enhancement

#85 Simulation: [bugfix] deadlock if `pause()` is called during simulation tick
  src/main/java/de/unistuttgart/informatik/fius/icge/simulation/Simulation.java
Labels: High Priority
